spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade-bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/swagger"
    tags-sorter: alpha

logging.level.org.springframework.web: DEBUG